spring:
  h2:
    console:
      enabled: true
      path: /db
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

database:
  driverClassName: org.h2.Driver
  url: jdbc:h2:~/springdb/DB_CLOSE_ON_EXIT=FALSE
  username: fiap
  password: fiap

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: validate

file:
  input: classpath:students_pre_registration.txt

sonar:
  projectKey: spring-service
  projectName: Spring Service
  projectVersion: 1.0
  sources: src
  language: java
  binaries: build/classes
  tests: junit
  dynamicAnalysis: reuseReports
  junit.reportsPath: build/test-reports
  java.coveragePlugin: jacoco
  jacoco.reportPath: target/jacoco.exec