INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin', '{noop}admin', 1);
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user', '{noop}user', 1);
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user', 'ROLE_USER');